//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSPBH2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLSP1Entities1 : DbContext
    {
        public QLSP1Entities1()
            : base("name=QLSP1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AnhBia> tbl_AnhBia { get; set; }
        public virtual DbSet<tbl_DanhSach> tbl_DanhSach { get; set; }
        public virtual DbSet<tbl_NguoiDung> tbl_NguoiDung { get; set; }
        public virtual DbSet<tbl_SanPham> tbl_SanPham { get; set; }
    }
}
