//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSPBH2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SanPham
    {
        public int IDSP { get; set; }
        public string MaSP { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> IDDS { get; set; }
    
        public virtual tbl_DanhSach tbl_DanhSach { get; set; }
    }
}
