//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSPBH2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DanhSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DanhSach()
        {
            this.tbl_SanPham = new HashSet<tbl_SanPham>();
        }
    
        public int IDDS { get; set; }
        public string TenDanhSach { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> IDDanhSachCha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SanPham> tbl_SanPham { get; set; }
    }
}
